language: 
  - R

cache: 
  - packages
  
sudo:
  - required

warnings_are_errors: 
  - true

addons:
    apt:
        packages:
            - libudunits2-dev
            - libnetcdf-dev
            - netcdf-bin
            - libproj-dev 

script: 
  - ./travis-tool/travis_timeout.sh travis_wait

## Use patched devtools
r_github_packages:
  - hadley/devtools@efa894ffa

after_success:
  - Rscript -e 'covr::codecov()'
