language: 
  - R

sudo:
  - required

warnings_are_errors: 
  - true

before_install:
  - chmod 755 ./travis-tool/travis_timeout.sh

script: 
  - ./travis-tool/travis_timeout.sh travis_wait

## Use patched devtools
r_github_packages:
  - hadley/devtools@efa894ffa
